namespace FPL.Console;

public static class IncludedPlayers
{
    public static readonly Dictionary<string, string> LockedPlayers = new()
    {
        // { "Wirtz", "MID" },
        // { "Cucurella", "DEF" },
        // { "Watkins", "FWD" },
        // { "Wood", "FWD" },
        // { "Kudus", "MID" }
        // {"Haaland", "FWD"}
    };
    public static readonly List<string> IncludeList = 
    [
        "Raya",
        "Sels",
        "Verbruggen",
        "Kelleher",
        "Sánchez",
        "Pickford",
        "Virgil",
        "Frimpong",
        "Richards",
        "Tete",
        "Gabriel",
        "Saliba",
        "Cucurella",
        "Van de Ven",
        "Romero",
        "Tarkowski",
        "Mykolenko",
        "Wan-Bissaka",
        "Diouf",
        "Milenković",
        "Murillo",
        "N.Williams",
        "Rodon",
        "Estève",
        "Richards",
        "De Cuyper",
        "Guéhi",
        "Gudmundsson",
        "Dorgu",
        "Konsa",
        "Muñoz",
        "Wirtz",
        // "M.Salah",
        "Palmer",
        "Gakpo",
        "Ndiaye",
        "Kudus",
        "Marmoush",
        "Foden",
        "Rice",
        "Minteh",
        "Saka",
        "Xhaka",
        "Anderson",
        "Gordon",
        "B.Fernandes",
        "Cunha",
        "Mbeumo",
        "Elanga",
        "Eze",
        "Sarr",
        "Semenyo",
        "Andersen",
        "Baleba",
        "Enzo",
        "Damsgaard",
        "Haaland",
        "Watkins",
        "João Pedro",
        "Solanke",
        "Wood",
        "Gyökeres",
        // "Ekitiké",
        "Bowen",
        "Mateta",
        "Welbeck",
        "Raúl",
        "Strand Larsen",
        "Thiago",
        "Füllkrug",
        "Muniz",
        "Obi",
        "Marc Guiu",
        "L.Miley",
        "A.Ramsey",
        "Devenny",
        "Ba"
    ];
    public static readonly List<string> BanList =
    [
        "Amad",
        "Cunha",
        "Ederson M.",
        "Tosin",
        "Mbeumo",
        // "Martinez",
        "M.Salah",
        "Maguire",
        "Minteh",
        // "A.Becker",
        // "Gvardiol",
        // "Beto",
        // "Saka",
        // "Xhaka",
        // "Baleba",
        // "Tielemans"
        // "Digne",
        // "Pope",
        // "Raya",
        // "Raúl",
        // "Gvardiol",
        // "José Sá",
        // "Mayenda",
        // "Flemming",
        // "Maguire",
        // "Botman",
        // "Schär",
        // "Rodrigo",
        // "Rice",
        // "Petrović",
        // "Richards",
        // "Tete",
        // "Ederson M.",
        // "Saka",
        // "A.Becker"
    ];
}